### ISSUE TITLE
Script

### ISSUE THREAD

**Issue by scottgarner** [processing/p5.js-video#11]
I just pushed a rough [new script](https://github.com/scottgarner/p5.js-video/blob/gh-pages/script.md). Please have at it and change any crazy wording or anything else that stands out.

Below are some notes on the different sections.

**Lauren's Intro**

This section will be more or less the same, but I think we should skip the gestures unless we have specific animations planned. We can at least show Lauren's name and do some kind of reveal when she says "p5.js".

**Dan's Intro**

Should we go straight into the circle demo or try a few quick full-screen examples again?

**Circle**

We could potentially add more steps here, like adding a <p> to show the value, but since this section is pretty tame we might want to keep it short.

I thought, too, that we might try highlighting just a few snippets instead of showing all of the code for a given example. So Dan could mention ellipse() in the circle example and have it appear on the screen? I guess I'm just worried about showing all of the code because it gets unwieldy pretty quickly, but isolated commands might not be very useful.

**Flocking**

The circles could also be more mouse-interactive, like color or size changes based on proximity. Or we could throw in some more sliders to control things like that. Maybe the color is based on the temperature?

**More Examples**

At this point, we could show a few more fleshed out examples without all of the lead-up. A simple generative drawing app, for example, or a piano built with the audio addon. Another option would be to expand the flocking example a little further and add something like wind chimes that would play a sound when particles collided.

**Dan's Closing**

We can pop back to Lauren here or have Dan do the outro—whatever works best.

**Lauren's Outro**

We could potentially animate in some bullet point-type stuff here, too.

**Comment by shiffman** [comment]
This is great, love the new script.  Some quick thoughts:
- I think we should definitely show some code even if it's just a few snippets.  We can do this in the "Circle" spot.  I think we should also maybe show `createSlider()` to see how simple that is.
- I love the idea of a piano.   For generative drawing, maybe we port the class "Yellowtail" by golan?

**Comment by shiffman** [comment]
FYI, I'm going out of town tomorrow for a week.  I think I'll try to shoot a new video the week of July 14th?

**Comment by scottgarner** [comment]
I like showing the simplicity of commands, too. `createSlider()` works particularly well. Do you think we break down the arguments in detail for something like `ellipse()`? I wonder if mentioning something like `getJSON()` would be good, too.

Enjoy your trip!

**Comment by shiffman** [comment]
I made some adjustments to [the script](https://github.com/scottgarner/p5.js-video/blob/gh-pages/script.md).  I added:
- some quick lines mentioning that the code will appear.
- some lines about Yellowtail and a generative piano example.  (I'm happy to do the port of Yellowtail and maybe Jason can help us with the piano, assuming we want to include these.)

Thoughts?

Lauren do you want to do the outro (I think that's a good idea?) or should I?

**Comment by scottgarner** [comment]
Looks great, Dan. The only thing I'm stuck on is how quickly the drawing and piano examples will pass. I've been thinking about these and haven't come up with a great solution.

Maybe we mention the drawing example second and let the user continue drawing through the end of your section or even all the way to the end of the demo. In that case it might make sense to just play a few tones as part of your explanation. Something like:

You can do a lot of exciting things with p5.js. It doesn't have to be visual, either, you can play with sounds. For example, you can generate tones in realtime and play a little song. (cue) You can also let the user choose what to draw by creating a generative drawing tool. Try dragging your mouse around to draw a picture then release and see what happens. (cue)

That approach to the sound breaks our "always interactive" rule, but I'm a little worried about the sound conflicting with the video. In the full demo of that concept, we could still show a little keyboard.

I think I'd also like to take a stab at a new drawing tool based on [something](http://scott.j38.net/interactive/trails/) I've been meaning to port from Cinder to the web. But if you'd prefer to do Yellowtail, that's totally fine.

**Comment by shiffman** [comment]
What if we try starting with sound, have it play a few notes, and when we get to the drawing example, have it trigger sound as you drag?  I guess we may have some issues with sound conflicting with the video though.   Or I could spend ask the user to play some notes and actually just stop and wait for 5-10 seconds?

Yes, let's do your drawing tool!

**Comment by scottgarner** [comment]
Stop and wait makes me a little nervous, but I do like the idea of combining the examples into a sound/drawing, tool. That's something I was imagining with Trails at some point, anyway.

I think we could implement some ducking (either real or faked with popcorn) so that while you were talking the tones wouldn't be too obtrusive. I'm all about strange, generative sound toys lately.

So we could have similar copy to the above and just add a line about how you can combine both the audio and drawing features into one tool.
