### ISSUE TITLE
CTA Panel

### ISSUE THREAD

**Issue by scottgarner** [processing/p5.js-video#12]
Here's what the final call to action panel looks like now:

![screen shot 2014-07-27 at 11 59 32 am](https://cloud.githubusercontent.com/assets/786436/3715628/465fee22-15ee-11e4-8da4-cfe42ba130b0.png)

@lmccart, I'm guessing there are already appropriate pages on either the p5 site or the wiki to link to, I just need the URLs. The example page and about page will probably be part of the video site.

"Transition Guide" is a little opaque, but "Transitioning from Processing"  is a little long for a button. Thoughts on a better way to put this?

**Comment by scottgarner** [comment]
The buttons all function now, we just need to settle on URLS and on content for the examples and about.

Right now View Examples takes you to another page on the site, but it could also just pop up like About.

**Comment by lmccart** [comment]
download p5.js http://p5js.org/download/
get started http://p5js.org/get-started/
transition https://github.com/lmccart/p5.js/wiki/Processing-syntax-conversion
view examples http://p5js.org/learn/#examples
contribute http://p5js.org/contribute

note that these links are not live yet, stick a site/ after p5js.org to get the temp location.

for examples, maybe they could be a subsection within the learn/#examples section on the website?

**Comment by scottgarner** [comment]
Showing examples on the main site sounds good to me. It would save redundant work on on editor.

I think the editing interface there could be simplified by using Ace and drawing everything in an iFrame. I was just working on that, but am having trouble getting it to work for sketches with and without a setup and draw at the same time.

I think I'll just make About link to this repository with a Readme so everything goes offsite.

**Comment by shiffman** [comment]
Ah, so should I just push examples I make re: #19 to https://github.com/lmccart/p5js.org?

**Comment by scottgarner** [comment]
I think that might be a good plan. @lmccart, could you look at the example viewer at http://hello.p5js.org/examples/. I think it might be nice to do something like that on the main site, though I'm having trouble running examples without setup().

I'm not clear on what makes p5 decide to add things like createCanvas to window and when exactly that happens.

**Comment by lmccart** [comment]
yeah, I'd be down to switch to ace for the main site examples. I didn't include it already because I thought it might be too heavy if there were multiple examples on one page like in the reference. Or are you thinking this would be just for the examples off the learning page and not for the examples in the ref?

The p5 library does not support code without either a setup or draw. I am doing some hacky stuff to support this for the reference examples (I think of these more as code snippets), but I would want any formal examples outside the ref to use setup/draw. 
https://github.com/lmccart/p5js.org/blob/master/site/js/render.js#L142

**Comment by scottgarner** [comment]
I just thought that an editor with syntax highlighting might be a little nicer than the current approach for editing with the text area, but I'm not sure how heavy it would get with multiple examples. Overall, ace seems pretty light unless you're actively manipulating text.

All of the links point to planned places, so I'll close this issue for now and we can continue discussing examples in #19.
