### ISSUE TITLE
Flocking Demo Performance

### ISSUE THREAD

**Issue by scottgarner** [processing/p5.js-video#13]
@shiffman, I've done quite a bit of tuning on all of the sketches, but the flocking demo is still pretty heavy and I'm worried it will bog down older machines with the video compositing happening.

I'm going to take a pass at combining a lot of the functions to avoid redundant loops, but I might need some help. Here's the current state:

http://hello.p5js.org/#120

**Comment by shiffman** [comment]
Awesome, yes I can help with optimizing this.  A couple of ideas:
- Computer a global center and average velocity for cohesion and alignment.
- Use global Vector objects to avoid creating tons of temporary objects (not sure if this matters in JS)
- Consider [binning](http://natureofcode.com/book/chapter-6-autonomous-agents/#bin-lattice-spatial-subdivision-82bc2210-253f-0130-bce9-7cd1c3f718ad)
- Use [magSq](http://processing.org/reference/PVector_magSq_.html)

It's running great for me, but I'm on a nice macbook pro.

**Comment by scottgarner** [comment]
I took a pass in /demos/flockingOptimized last night. Most of what I did involved restructuring.
- I collapsed all of the loops in the Flock class into a single loop.
- I combined separation, alignment and cohesion into a single loop, which was probably the biggest increase in performance.
- I tried to eliminate all of the temporary pVectors, which did seem to have some overhead
- The above two changes let me change the separation, alignment and cohesion logic so that both the current boid and the compared boid are updated at the same time. This way, you don't have to loop through every boid for every boid. That's a terrible explanation, but in other words the first boid loops through every boid except itself, the second boid loops through every boid starting with the third one, and so on until the last boid, which doesn't loop through any because it has already been updated.

Experimenting with the PVector functions ended up increasing performance quite a bit, too.

If you could look things over to make sure I didn't break anything, that would be great. Performance is much better for me now on my 2011 MacBook Air with a mediocre GPU, but if you can see any other places to tune, please do!

**Comment by shiffman** [comment]
Seems pretty great, I just replaced distance with a manual distance calculation with no square root.  Minor change, but maybe helps a little bit.

https://github.com/scottgarner/p5.js-video/commit/153e5fa345777117fdf58ccf081147ecf820486d

We could also just try fewer boids (like 75?) and see if visually it is just as nice but faster.

**Comment by scottgarner** [comment]
Thanks for checking!

The new code runs pretty well at even 300 boids on my machine now. It
stuttered a little before at 75, so I think we're in good shape.

I've been thinking about some auto performance tuning stuff, but it's
probably not necessary here.
