### ISSUE TITLE
pause button?

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-video#15]
Even though we've deleted the pause and play with the code feature, it feels like a subtle pause button might be useful.   (Maybe we try only this but we could also consider a "jump back 10 seconds button as well").

**Comment by scottgarner** [comment]
I can definitely add a pause button for the video. The sketch wouldn't pause without additional logic. Maybe p5 should have a pause() method? 

Jumping is more tricky because each sketch has a lot of timed events and jumping over them could break things. (Like the weather JSON call.)

**Comment by lmccart** [comment]
I think the loop()/noLoop() is supported to function as pause() for sketches, right?

**Comment by shiffman** [comment]
Ah, I was thinking that the sketches would not pause, only the video.  This way if someone wanted to interact a bit more they could pause and play.

**Comment by scottgarner** [comment]
Mouse events and such would still fire, but that's probably enough for our
purposes.

**Comment by scottgarner** [comment]
Ah, right. Dan. That's probably better anyway. I'll use noLoop() where
required and otherwise just pause the video.
