### ISSUE TITLE
automatic slider demo

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-video#16]
should the slider slide back and forth automatically when I first reference that it will change the color?

**Comment by scottgarner** [comment]
I think a lerp would be hard to time, but I can go back and set the color at a few points the same way I do with the drawing finger.

**Comment by scottgarner** [comment]
A lerp turned out to be smoothest after all.

**Comment by shiffman** [comment]
Re-opening this.  A minor point, but the slider should probably finish on the left or else live above the video. Right now where it ends, the clickable part is being obscured by me.

**Comment by scottgarner** [comment]
I have an overlay layer now, but in testing it seemed a little strange to separate it.

I added another lerp to take it to the left and it seems to work well.

**Comment by shiffman** [comment]
works great now, thanks!
