### ISSUE TITLE
Canvas is 1/2 size

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-video#18]
Chrome Version 36.0.1985.125 Mac OS X

![screen shot 2014-07-29 at 10 25 51 am](https://cloud.githubusercontent.com/assets/191758/3736296/4bdc1166-172c-11e4-8608-9218070880b2.png)

**Comment by scottgarner** [comment]
Did you resize your browser? 

Currently there's no logic to resize the canvas when the window resizes. Is this something that could work with size() in a sketch?

**Comment by lmccart** [comment]
it could be related to the hdpi support scaling. @scottgarner are you manually setting the width/height of the canvas div anywhere? this should be set by p5. I'll take a look at this.

**Comment by lmccart** [comment]
relevant scaling stuff here:
https://github.com/lmccart/p5.js/blob/master/lib/p5.js#L3163

**Comment by shiffman** [comment]
Ah, I am noticing this problem on a retina.  (I have not resized the browser.)  Can't check now on a non-retina but wouldn't be surprised if this is the issue.

**Comment by lmccart** [comment]
I'm guessing it is as I'm on non-retina and it sounds like @scottgarner also has an older machine. I'll review this and make sure it's all working correctly on the library end. I'm not sure I've tested it with instance mode.

**Comment by scottgarner** [comment]
I create the initial canvas in that sketch like this:

`sketch.createCanvas(window.innerWidth,window.innerHeight);`

Should it be AUTO? It already lives in a div that fills the screen.

**Comment by shiffman** [comment]
This is working fine on my macbook air.  However, I am seeing this from time to time (top of scene cut-off).  It might be something I'm doing, trying to reproduce more consistently.

![image](https://cloud.githubusercontent.com/assets/191758/3744327/6ba76e58-178d-11e4-80de-e745a3a72b82.png)

**Comment by scottgarner** [comment]
Some of the sketches, like the labels and circle, are positioned dynamically relative to the video. In this case, it looks like your window is just a little too short. I've thought about experimenting with scaling the video within the browser, but that will make the relative positioning a little crazy.

**Comment by shiffman** [comment]
Maybe we don't scale the video, but just push the labels a bit down if we detect a sketch height below a certain threshold?  All in all, this isn't a high priority as everything else appears fine.

**Comment by scottgarner** [comment]
I guess the other benefit to scaling is for people with huge displays. I'll
experiment a bit.

I may end up restyling these labels completely when I do the intro so that
positioning won't be an issue.

**Comment by scottgarner** [comment]
Something just occurred to me. @shiffman, is the canvas really half size or is it something in the borders() function? I can't quite tell from your screenshot.

**Comment by shiffman** [comment]
If this helps, when I pause the video and take over main.sketch and set the background to grey I see:

![screen shot 2014-07-30 at 12 30 19 pm](https://cloud.githubusercontent.com/assets/191758/3752339/e484b5fa-1806-11e4-9c89-d46ee3bfab29.png)

log of my console:

```
main.sketch.width;
1128
main.sketch.height
779
143.708132 main.js:15
{left:533, top:29} main.js:18
main.sketch.noLoop();
undefined
main.sketch.background(100);
undefined
```

My screen is 1440x900 so this seems like the right resolution just appearing smaller.

**Comment by scottgarner** [comment]
@lmccart, I've been doing some testing on a retina iPad mini. I haven't figured out the flocking example, but the painting example seems to fail like this:

1) I create a canvas at 1280x800 and p5 doubles this per the pixel ratio and displays it at half the size.
2) I create offscreen buffers at 1280x800 with createGraphics. p5 doesn't double these.
3) I draw the buffer canvases to the main canvas and they only fill part of the screen because the ratio isn't accounted for, even though from a user perspective they were set to the same size.

You can see this behavior on non-retina displays by manually setting this._pixelDensity to 2.

I think it would be nice to offer a means to disable the pixel adjustment, too. The iPad mini works fine with the ratio set to 1, but setting it to 2 means four times the pixels and it really bogs down.

**Comment by lmccart** [comment]
ohh wow good find, thank you! I will fix this this afternoon. and an option to turn off pixelDensity scaling.

**Comment by lmccart** [comment]
for now, if you want to disable scaling you can add

```
sketch._pixelDensity = 1;
```

before the createCanvas call.

**Comment by scottgarner** [comment]
Great, thanks Lauren.

**Comment by scottgarner** [comment]
@shiffman, I've disabled the pixel density compensation for now. Can you confirm that it works on your retina display?

**Comment by shiffman** [comment]
yup, works great, thanks!

**Comment by lmccart** [comment]
@scottgarner the graphics buffer should be scaling the same as the canvas now if you do want to use the pixel density compensation. but maybe better to leave it off for performance?

**Comment by scottgarner** [comment]
Great, it looks like the buffers are created at the proper size, though now
they're double size when shown in the dom. It looks like you'll need the
same css trick for width and height to cut them in half.

Theres also a problem with mouseX and mouseY not corresponding to the right
place on a pixel-doubled canvas. I think there may be a problem with width
as well?

I'll try to make a little sketch that demos the problems later this morning.

**Comment by scottgarner** [comment]
Okay, I think I found the cause of the problem, but I didn't dig into a solution.

`clear()` seems to be throwing off the pixel adjustment so that sketch dimensions and mouse positions don't add up. It also throws away stroke and fill settings specified in `setup()`.

And as mentioned above, createGraphics elements need css sizing to show them half size.

Here's a test page:

http://hello.p5js.org/test/retina.html

**Comment by lmccart** [comment]
for the graphics element, isn't the idea here that it's not shown in the dom, it's an offscreen rendering buffer? or are you just using it as a second canvas? either way, I added the css scaling just now, thanks for the test page, I'll look into the problem with clear. I was trying a trick that is supposed to be performance optimized for clearing the canvas but looks like it sort of nukes everything.

**Comment by lmccart** [comment]
ok test page looks good with this commit https://github.com/lmccart/p5.js/commit/1e5e0e3312fcd0ea8997dc1a5182a8614c2bb38f

**Comment by scottgarner** [comment]
For the painting sketch, I was using it for offscreen buffers and that's definitely the normal usage in Processing.  For other demos, I was using it to create graphical elements that were incorporated in other html. The wind gauge graphic, for example, and the label arrow. 

Maybe that shouldn't be supported behavior? Intuitively, it seems like you should be able to create multiple graphical elements and mix them up with other dom elements, but I could see making a case either way.

Ah, right. I've used that width trick before, but I don't think it's the fastest way anymore, even aside from all of the resets. [This thread](http://stackoverflow.com/questions/2142535/how-to-clear-the-canvas-for-redrawing) has a lot of discussion on the topic, but I haven't done any speed testing myself.

**Comment by scottgarner** [comment]
Great, looks like the `clear()` fix took care of all of the problems with the painting and flocking sketches.

I'm going to leave pixel density set to 1 for performance until I can do some testing on retina machines, but it's good to know that everything will work.

**Comment by lmccart** [comment]
yeah makes sense about the buffers. I think it's simple enough to support p5.graphics as onscreen elements, too, though it'll be hidden by default. I think I need to do a little more testing of clear to see what happens when there are transforms applied, but I think as long as you call it at the beginning of draw it should be ok.
