### ISSUE TITLE
Look and Feel

### ISSUE THREAD

**Issue by scottgarner** [processing/p5.js-video#2]
![frame](https://f.cloud.github.com/assets/786436/2177080/2195049e-95f4-11e3-8389-9a453226819d.jpg)

Here's a very quick mock-up. The basic idea is that Dan lives in whiteboard land and whatever he talks about happens behind him in a felt marker look. The animations aren't in the footage, but are actual p5.js sketches running and interacting with the viewer's mouse.

It makes production trickier, but I think the best experience would require Dan keyed out (seriously.js?) so that things can easily move behind him. The whole video could simply be a few minutes long and cover a handful of possible sketches.

**Comment by shiffman** [comment]
This is a great start.

You are probably right about the greenscreen thing though I do love the idea of being able to actually draw and have stuff interact with the drawing.  Would it work to just shoot on white and then have canvas elements drawn on top?  I guess the problem is that I can't be separated from the background. . . hmmm. . . 

"pause and view code" is fantastic.

**Comment by scottgarner** [comment]
I have a quick test [site up](http://scottgarner.github.io/p5.js-video/) up so we can drop in video when we're ready. I think the easiest thing to start with would be you against the green screen, which we can key out with seriously.js.

**Comment by shiffman** [comment]
awesome, hope to record a test today.

**Comment by shiffman** [comment]
There are so many problems with this video but it's something we can at the very least begin with.  I'll try to get to another, more thoughtful pass next week.

https://vimeo.com/87320014

**Comment by scottgarner** [comment]
This is amazing!

I've got start on this, but it's going to take some doing to get p5, popcorn and seriously all working happily together.

**Comment by scottgarner** [comment]
The basic building blocks are working, though everything is very rough: http://scottgarner.github.io/p5.js-video/

I have a console event triggering at the time of the rectangle, the next big challenge is swapping out the p5.js code at the appropriate time.

**Comment by shiffman** [comment]
did you cut off any of the video at the bottom?  I think maybe i need to shoot myself a tiny bit wider or get a tiny bit higher.  A tiny point, but it feels a bit too sunken?

**Comment by scottgarner** [comment]
The video was bumped down! Weird CSS problem. I just pushed a lot of tweaks from the last two weeks in f7f2919951. A lot of it involved experimenting with the new p5.js instancing stuff and the basics are there, though there's not yet a way to kill a sketch. I'm guessing I'll just use exit() once that's implemented.

I've also done some more experimenting to get a cleaner key on the video. I need to just dig in to that shader to really figure out what they're doing, but I think if we can get a sharper video with more even lighting, we'll be in good shape. Part of why the edges are so bad right now is that the video was a little fuzzy.
