### ISSUE TITLE
Intro popups

### ISSUE THREAD

**Issue by scottgarner** [processing/p5.js-video#21]
Just a few animations to go with Lauren's intro. I was thinking of drawing and animating the logo slightly.

**Comment by scottgarner** [comment]
To keep things quick and basic for the intro, I think I'll just show an animated version of the p5 logo when @lmccart mentions it and then list off some bullet points when she says "the core ideas of Processing".

What four or five concepts might you list as the core ideas? A few that come to mind:
- Beginner Friendly
- Powerful Drawing Tools
- Video and Audio Support
- Expandable With Add-ons
- ???

**Comment by shiffman** [comment]
cc @reas for his thoughts.  One additional idea:
- free to download and open source

I'm not sure if "Powerful Drawing Tools" is the right language maybe something about visual arts?

**Comment by scottgarner** [comment]
"Free to download and open source" was a bit long for one line, so I broke it into two bullets. I dropped the drawing line for now and can easily add anything else.

**Comment by lmccart** [comment]
I think it could be "free and open source"

**Comment by REAS** [comment]
I think separating the ideas of "free to download" and "open source" is a good idea. They are separate choices and ideas.

**Comment by scottgarner** [comment]
Just found a handy list here: https://github.com/lmccart/p5.js/wiki/Starting-points#processing-core-values

How about revising the current list to:

Programming for the Arts
Made for Teaching
Extensible with Add-Ons
Free to Download
Open Source

**Comment by shiffman** [comment]
Yes, this is great!

**Comment by lmccart** [comment]
whoops, should've dug that up sooner, updated list looks great.
