### ISSUE TITLE
safari broken?

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-video#27]
getting this error, mac os x 10.9 safari Version 7.0.5 (9537.77.4)

![image](https://cloud.githubusercontent.com/assets/191758/3744300/d5284984-178c-11e4-93bc-4c1298ec9eb8.png)

**Comment by scottgarner** [comment]
Safari 7 doesn't support WebGL unless you enable it. Seriously.js should be checking for compatibility and showing an error message, but maybe I broke something.

**Comment by shiffman** [comment]
Got it, yes, enabling webgl fixes it.  Will leave this open re: resolving error message.

**Comment by shiffman** [comment]
Fix works.
