### ISSUE TITLE
use p5 asterisk as "something else" icon?

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js-video#31]
very minor, and @scottgarner it's totally your call whether it fits with the graphic language you have going on there. but the file is here if you want to use it https://github.com/lmccart/p5js.org/blob/master/img/thick-asterisk-alone.svg.

**Comment by scottgarner** [comment]
Thanks, Lauren. I was mostly just being lazy and using images provided by Font Awesome, but I was able to easily drop in the image and still use the fa spinner animation.
