### ISSUE TITLE
interactive circles timing

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-video#33]
I think maybe the circles should avoid the head area and the mouse immediately.   If I'm correct the current behavior is that the interactivity turns on when I mention it.   It feels like they should always be interactive and I'm just reminding the viewer when I reference it.  Thoughts?

**Comment by scottgarner** [comment]
Sure. That was leftover from an early version when there was only one repel target that I switched form head to mouse, but with two targets we can definitely leave them.

**Comment by shiffman** [comment]
Great, working great now.
