### ISSUE TITLE
Social Links

### ISSUE THREAD

**Issue by scottgarner** [processing/p5.js-video#34]
Thoughts on adding social links to the CTA page in the lower right corner after the pause button vanishes? 

I'm pretty indifferent toward that sort of thing, but it's easy enough to add.

**Comment by lmccart** [comment]
I'm indifferent also, I say skip it, it's easy enough to share the link just by grabbing it from the address bar. unless you think it adds something visually to the page.

**Comment by scottgarner** [comment]
Skipping sounds good to me.
