### ISSUE TITLE
Final Testing for Launch

### ISSUE THREAD

**Issue by scottgarner** [processing/p5.js-video#36]
Everything seems to work on the devices and platforms I've tested so far. The only exception is on an iPad running the iOS 8 beta because of the way that device loads videos, but iOS 8 won't be out until next month so I just need to come up with a fix before then.

I was thinking of posting the demo to the ITP alum list for some last minute testing unless there are any objections.

**Comment by lmccart** [comment]
sounds great, go for it!

**Comment by lmccart** [comment]
ready to go live?

**Comment by scottgarner** [comment]
Everything looks good to me and no new issues came up from the Alum list.
