### ISSUE TITLE
Example Integration

### ISSUE THREAD

**Issue by scottgarner** [processing/p5.js-video#4]
I made some updates and wanted to lay down the current approach to handling examples. You can see how things are going here:

http://scottgarner.github.io/p5.js-video/#70

So, every example that runs in the video is stored as a object in js/examples.js. These examples are loaded and modified from popcorn events in js/script.js. They also hold a reference to a simplified version of the example to show the user, which is stored in _includes/examples.html.

One thing to note is that everything placed on the screen can be positioned absolutely (relative to 0,0 in the browser) or relative to the video, so that things maintain their relationship to Dan no matter how the browser is scaled. To help with event creation and timing, you can click anywhere on the page and get a relative position and timecode in the console. You can also jump to a section of the video by appending a location hash with the time (as in the URL above).

There are still some funny things about clearing and unloading and I'm not sure everything happens in the absolute best place, but I think I've got a fairly solid foundation.

I'll take another pass to add more incidental events. Dan, maybe you could work out the particle examples? Integrating them might be fussy, so if you an build them standalone I can work on finding the best way to include them.

**Comment by shiffman** [comment]
Ok, there is a pass at more examples here:

https://github.com/scottgarner/p5.js-video/tree/gh-pages/examples

The particle ones are hacked together to emulate the behavior I discuss in the video.  I should put more time into them to be more thoughtful about structuring them for beginners. Once we get them integrated I can make further edits / adjustments.
