### ISSUE TITLE
Greenscreen visible in Chrome?

### ISSUE THREAD

**Issue by GanWeaving** [processing/p5.js-video#40]
![capture](https://cloud.githubusercontent.com/assets/5080144/3829497/252a63c8-1d81-11e4-8714-3537cbd6d377.JPG)

**Comment by GanWeaving** [comment]
It works fine in my Firefox browser but not in Chrome.

**Comment by shiffman** [comment]
OS / browser version?

**Comment by GanWeaving** [comment]
Windows 7
Chrome 38
Firefox 31

**Comment by scottgarner** [comment]
Thanks, @Xeronimo74. I tested with Chrome 36 on Windows 7, but not 38. I'll grab it and give it a shot.

Any errors in the developer console?

**Comment by scottgarner** [comment]
Hmm. I tested Chrome (36), Chrome Beta (37) and Chrome Canary (38) in Windows 7 without any problems. Would you mind taking a look the demo on the homepage of http://seriouslyjs.org to see if that works?

**Comment by GanWeaving** [comment]
Hi, yes, seriouslyjs seems to work correctly. Still the same green screen problem with hello.p5js.org though ... The console gives me these errors: 
18 : CS -> BG : FAILED closepopuptoplevel chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/onloadwff.js:77
21 : CS -> BG : FAILED closepopuptoplevel chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/onloadwff.js:77
Font from origin 'http://fonts.gstatic.com' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://hello.p5js.org' is therefore not allowed access. The response had HTTP status code 403. hello.p5js.org/:1
Failed to load resource: the server responded with a status of 403 (Forbidden: header 'Content-Type' value denied) http://fonts.gstatic.com/s/inconsolata/v8/BjAYBlHtW3CJxDcjzrnZCI4P5ICox8Kq3LLUNMylGO4.woff2
Font from origin 'http://fonts.gstatic.com' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://hello.p5js.org' is therefore not allowed access. The response had HTTP status code 403. hello.p5js.org/:1
Failed to load resource: the server responded with a status of 403 (Forbidden: header 'Content-Type' value denied) http://fonts.gstatic.com/s/inconsolata/v8/BjAYBlHtW3CJxDcjzrnZCIbN6UDyHWBl620a-IRfuBk.woff

**Comment by scottgarner** [comment]
Thanks for testing, @Xeronimo74.

It looks like your LastPass extension is throwing some errors, but i don't see how that could affect the keying. Those font security errors are unusual, too, but also seem unrelated. Are you running any other exertions that might be causing problems?

Also, would you mind trying out this simplified chroma test: http://hello.p5js.org/test/chroma.html

Just hit play and see if playing with the sliders affects the key. Thanks!

**Comment by Jdakotapowell** [comment]
Seeing a green screen with the Chrome browser.

**Comment by scottgarner** [comment]
Hi @Jdakotapowell. Can you provide your browser and OS version along with any errors in the console?

**Comment by Jdakotapowell** [comment]
Chrome - Windows Vista - as per console errors - can get bk to you on Sat -
on a deadline & sweating it out!

**Comment by scottgarner** [comment]
@Jdakotapowell Thanks for the feedback and take your time.

**Comment by nolanbjohnson** [comment]
Chrome (Version 36.0.1985.125 m) most up to date -- Windows 8. Don't see any console errors. Tried the chroma test above as well, but sliders have no effect.

**Comment by scottgarner** [comment]
Thanks for testing, @nolanbjohnson. Would you mind trying the demo at http://seriouslyjs.org to see if that works?

**Comment by nolanbjohnson** [comment]
the demo does work for me.

**Comment by scottgarner** [comment]
So strange!  @brianchirls, mind if I rope you in here?

**Comment by nolanbjohnson** [comment]
Correction...I was not getting the full effect on the demo. The buttons applied a filter but did not completely replace the green screen. Just watched it on my mac and saw the difference. Sorry for the confusion.

**Comment by brianchirls** [comment]
This is a really tough one. Works fine on my Windows machine. And there are no obvious errors in the console.

So let's see if we can determine if it's Seriously.js in general or just the chroma key effect. @nolanbjohnson, @Xeronimo74 and @Jdakotapowell can you try out this page and let us know what you see?
http://brianchirls.github.io/Seriously.js/examples/animate/

There should be a canvas with an animated wipe effect going back and forth between some colored pencils and a toy robot with a purple pinwheel. Also, please check the console and let us know if anything shows up there.

And if you have the time, maybe you could list which browser extensions you have installed? We could see if there's anything you all have in common.

Thanks for your debugging help, everyone.

**Comment by GanWeaving** [comment]
Hi, I see that swipe effect. Plus a fine line of white dots at times (screenshot: http://i.imgur.com/3L8XYxT.jpg) ... No errors in the console.

As for the browser extensions: http://i.imgur.com/jwgju64.jpg , http://i.imgur.com/sJYl60h.jpg

**Comment by GanWeaving** [comment]
As for the Chroma test page, I'm seeing a green screen too. And the sliders don't seem to have an effect.

**Comment by brianchirls** [comment]
Ah those white dots are definitely not supposed to be there. Let me see if I can fix that...

I'm not too hopeful that the extensions will prove anything, but let's see what the others post and see if there's any overlap.  thanks again.

**Comment by nolanbjohnson** [comment]
Ditto @Xeronimo74 on the swipe effect and the white dots. Don't see any overlap in extensions. 
![image](https://cloud.githubusercontent.com/assets/3077509/3857203/036246c6-1f01-11e4-8629-3f8559cbe0b4.png)

**Comment by brianchirls** [comment]
Okay, I think we can rule out the extensions. I suspect it has something to do with the way your GPU/drivers handle the branching in the shader. Can you guys try out this test for me? It's a modified version of the split effect that I hope will not have the white dots. If that's the case, then I have an idea of how I can fix the chroma effect too.

http://jsbin.com/zecoq/1

For comparison, here's the same thing using the original split effect, which should have white dots.
http://jsbin.com/hadej/1

Also, can you tell us what GPU hardware you're using?

Thanks,
B

**Comment by GanWeaving** [comment]
Yes, the second one has the dots while the first one does not.

I've got an integrated graphics card from Intel (this is my work PC) ...

**Comment by brianchirls** [comment]
Ah, excellent. I'll make an issue for this over at the Seriously.js repo and will see if I can fix Chroma key. May take me a day or two.

**Comment by scottgarner** [comment]
Thanks for jumping in here, Brian. I really appreciate it.

**Comment by brianchirls** [comment]
No problem. I want to see these issues solved for Seriously as well. It's looking like a long list of effects that may be affected.

We should probably do a call one of these days to go over a few different things that may affect your video piece, what could be fixed and what could be improved.

**Comment by brianchirls** [comment]
Here's an example using a modified chroma key effect. Does it work?

http://jsbin.com/dijog/1

**Comment by nolanbjohnson** [comment]
I don't see a green screen (it's a full white background) but no visuals either. Not sure if it's helpful, but there's a lot of aliasing around the edges.

**Comment by brianchirls** [comment]
Thanks. Do you hear the audio?

**Comment by brianchirls** [comment]
Updated to make video controls visible, so you can make sure it's playing.
http://jsbin.com/dijog/2

**Comment by nolanbjohnson** [comment]
Yep, audio is good.

**Comment by brianchirls** [comment]
@nolanbjohnson just to be thorough, did the modified split effect work for you? i.e. is there the line of white dots here? http://jsbin.com/hadej/1

**Comment by nolanbjohnson** [comment]
yes, I do see the dots.

**Comment by darkyen** [comment]
@nolanbjohnson can you tell me your output for chrome://gpu and then windows information for the gpu and driver via dxdiag  ??

**Comment by nolanbjohnson** [comment]
Will do tomorrow morning @darkyen. Don't have my work laptop with me.

**Comment by nolanbjohnson** [comment]
chrome://gpu output:
Graphics Feature Status
Canvas: Software only, hardware acceleration unavailable
Flash 3D: Software only, hardware acceleration unavailable
Flash Stage3D: Software only, hardware acceleration unavailable
Flash Stage3D Baseline profile: Software only, hardware acceleration unavailable
Compositing: Software only and threaded. Hardware acceleration unavailable.
Rasterization: Software only. Hardware acceleration disabled.
Video Decode: Software only, hardware acceleration unavailable
Video Encode: Software only, hardware acceleration unavailable
WebGL: Software only, hardware acceleration unavailable
Driver Bug Workarounds
clear_uniforms_before_first_program_use
disable_d3d11
exit_on_context_lost
Problems Detected
GPU rasterization is whitelisted on N4, N5, N7 and Moto X: 362779
Disabled Features: gpu_rasterization
Some drivers are unable to reset the D3D device in the GPU process sandbox
Applied Workarounds: exit_on_context_lost
The Mali-Txxx driver does not guarantee flush ordering: 154715, 10068, 269829, 294779, 285292
Applied Workarounds: use_virtualized_gl_contexts
TexSubImage2D() is faster for full uploads on ANGLE
Applied Workarounds: texsubimage2d_faster_than_teximage2d
Clear uniforms before first program use on all platforms: 124764, 349137
Applied Workarounds: clear_uniforms_before_first_program_use
Using D3D11 causes browser crashes on certain Intel GPUs: 310808
Applied Workarounds: disable_d3d11
Accelerated rasterization has not been enabled or is not supported by the current system.
Disabled Features: rasterization
Version Information
Data exported   8/12/2014 11:02:34 AM
Chrome version  Chrome/36.0.1985.125
Operating system    Windows NT 6.3
Software rendering list version 8.7
Driver bug list version 6.1
ANGLE commit id d3d870647655
2D graphics backend Skia
Command Line Args   Files (x86)\Google\Chrome\Application\chrome.exe" --flag-switches-begin --flag-switches-end --disable-gpu --high-dpi-support=0
Performance Information
Graphics    5.2
Gaming  5.2
Overall 5.2
Driver Information
Initialization time 0
Sandboxed   false
GPU0    VENDOR = 0x8086, DEVICE= 0x0416
Optimus false
AMD switchable  false
Desktop compositing Aero Glass
Driver vendor   Intel Corporation
Driver version  10.18.10.3496
Driver date 3-11-2014
Pixel shader version  
Vertex shader version  
Machine model name  
Machine model version  
GL_VENDOR  
GL_RENDERER 
GL_VERSION  
GL_EXTENSIONS  
Window system binding vendor  
Window system binding version  
Window system binding extensions  
Direct rendering    Yes
Reset notification strategy 0x0000
Diagnostics
... loading ...
Log Messages
[8000:3720:0808/155921:ERROR:gles2_cmd_decoder.cc(6078)] : [.WebGLRenderingContext]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering or is not 'texture complete'
[8000:3720:0808/164104:ERROR:gles2_cmd_decoder.cc(6078)] : [.WebGLRenderingContext]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering or is not 'texture complete'
GpuProcessHostUIShim: The GPU process exited normally. Everything is okay.

**Comment by nolanbjohnson** [comment]
@darkyen 
and windows:
![image](https://cloud.githubusercontent.com/assets/3077509/3893473/19cd1912-223b-11e4-8a95-9d34605049cf.png)

**Comment by brianchirls** [comment]
@Xeronimo74 Can you tell me if the modified Chroma effect works?

http://jsbin.com/dijog/1

**Comment by brianchirls** [comment]
@nolanbjohnson: Thanks for posting that info. I talked to @darkyen and he wasn't able to replicate your problem. We're running out of options here...

The last thing I can think of is to try running the [WebGL Conformance Tests](https://www.khronos.org/registry/webgl/sdk/tests/webgl-conformance-tests.html). If you can paste the results here, I can try to see if it's picking up any quirks in your particular implementation. It will take a few minutes to run. When it's done, you can click "display text summary" and paste in the list of failures.

Chrome on my machine doesn't quite pass ALL of the tests, but maybe I can see if yours fails different ones from mine.

**Comment by brianchirls** [comment]
@nolanbjohnson I notice you're running Chrome with the `--disable-gpu` option. Did you set that up yourself? How come?

Maybe if you try running Chrome without that, you'll see different results. Or maybe it will crash. (That would count as "different," I think.)

**Comment by GanWeaving** [comment]
@brianchirls yes it works, white background

**Comment by brianchirls** [comment]
Great! Thanks, @Xeronimo74. So I'll fix this under [the ticket](https://github.com/brianchirls/Seriously.js/issues/69) over at my repo, which you are welcome to follow and comment on. I will also take a stab at refactoring other plugins to hopefully avoid the same problem.

**Comment by GanWeaving** [comment]
ok, cool!

**Comment by brianchirls** [comment]
@scottgarner The chroma effect is updated on the develop channel. Feel free to try it out. It should work the same for most people and solve the problem for @Xeronimo74.

https://github.com/brianchirls/Seriously.js/blob/develop/effects/seriously.chroma.js

**Comment by nolanbjohnson** [comment]
@brianchirls, when I run the WebGL test it goes fine for a bit and then everything starts failing.

This seems to be the recurring error msg:
FAIL Unable to fetch WebGL rendering context for Canvas
failed: context does not exist.

**Comment by nolanbjohnson** [comment]
Not sure why --disable-gpu option is there, @brianchirls. Though, when I try http://jsbin.com/dijog/1 it also works for me--white background.

**Comment by scottgarner** [comment]
Everything looks good so far on my end with the chroma effect from develop. Thanks, @brianchirls.
