### ISSUE TITLE
Error (incorrect?) about WebGL compatibility shown on Chrome for Android 

### ISSUE THREAD

**Issue by CraigStuntz** [processing/p5.js-video#43]
When I visit hello.p5js.org on Chrome Android Beta 37 with the WebGL flag enabled (which is the default setting), I see:

> Your browser doesn't appear to support WebGL or it isn't enabled. Visit get.webgl.org to learn more or try the latest version of Chrome.
> 
> Your browser doesn't support all of the features required for this demo. Please consider using the latest version of Chrome.

It's not clear to me if that's just incorrect browser sniffing or if the WebGL support in Chrome Android really won't work, but in either case it's not a particularly helpful message.

**Comment by scottgarner** [comment]
Thank you, Craig. We're using feature detection rather than browser sniffing, but it's still an inexact science at best. 

There's definitely a bug here because you're seeing what should be two separate messages. 

I'll double check the logic and work on more descriptive error text. 

—

**Comment by scottgarner** [comment]
I've been using the compatibility check in Seriously.js because Modernizr's checks don't work with the latest version of Safari. It might be better to switch to the check that happens at getwebgl.org or the one included in three.js.

@CraigStuntz, would you mind checking both seriouslyjs.org and get.webgl.org on that device?

**Comment by CraigStuntz** [comment]
Neither indicate WebGL support. 

Seriously:

> Sadly, we are unable to get Seriously.js to work on your computer. Sometimes WebGL gets a bit weird with certain graphics hardware and drivers. Please have a look here for more information.

get.webgl.org:

> Hmm. While your browser seems to support WebGL, it is disabled or unavailable. If possible, please ensure that you are running the latest drivers for your video card.

Some of the WebGL Chrome experiments work; others do not. I'm using a Nexus 10.

**Comment by scottgarner** [comment]
Very strange. I'm guessing the Three.js detector will also throw an error:

http://threejs.org/examples/webgl_geometries2

Looking at the Chromium issues, I don't see anything right away that would totally screw up feature detection like this, but there are quite a few WebGL-related problems with Chrome for Android. [This one](https://code.google.com/p/chromium/issues/detail?id=358198&q=webgl&colspec=ID%20Pri%20M%20Iteration%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified) in particular seems like it would break Seriously.js.

I'm not totally clear on whether it would work in the stable version (36) or in the canary version (38), but I'd prefer not to add catches for beta browser versions.

**Comment by CraigStuntz** [comment]
The three.js detector shows:

> Your graphics card does not seem to support WebGL.
> Find out how to get it here.

On both stable and beta. I don't have canary on this device.

**Comment by scottgarner** [comment]
Thanks for testing, Craig.

While the Modernizr test just tries to look for features, these other tests actually try to create and access a WebGL context to determine compatibility, so if they throw an error, it definitely seems like a problem with the browser's WebGL implementation.

The best thing I can recommend is to [file a bug](https://code.google.com/p/chromium/issues/list) for Chromium or comment on an existing bug that matches your results.
