### ISSUE TITLE
hello.p5js.org text for non-WebGL browsers could be more helpful 

### ISSUE THREAD

**Issue by CraigStuntz** [processing/p5.js-video#44]
If you visit hello and the site doesn't think your browser supports WebGL, the page  is fairly unhelpful. There are no links to or description of, for example, what p5 actually is.

**Comment by scottgarner** [comment]
Very good point. I'll link to p5js.org for users that can't view the demo. —

**Comment by lmccart** [comment]
maybe we just show the message and redirect after a few seconds to p5js.org?

let's also make sure it's clear in the error message that webgl isn't required for p5.js itself. maybe something like:

"Sorry! Your browser doesn't support all of the features required for this intro video demo, but you can continue to p5js.org to learn more about the library."

**Comment by scottgarner** [comment]
There are technically two error messages, though a bug was causing them both to be displayed. One for WebGL:

_Your browser doesn't appear to support WebGL or it isn't enabled. Visit <a href="http://get.webgl.org/">get.webgl.org</a> to learn more or try the latest version of <a href="http://google.com/chrome/">Chrome</a>._

And one for general feature detection (webaudio, csstransforms, etc.):

_Your browser doesn't support all of the features required for this demo. Please consider using the latest version of <a href="http://google.com/chrome/">Chrome</a>._

The only place you'll likely ever see the second one is in IE 11, which bafflingly supports WebGL but not the Web Audio API. It isn't strictly necessary to have two different errors, but it has become fairly common practice to link to get.webgl.org for WebGL errors.

In both cases you'll now get this line: 

Don't worry, you can still learn all about p5.js at <a href="http://p5js.org/">p5js.org</a>.

Happy to change the wording anywhere to make it more clear.
