### ISSUE TITLE
overall progress info?

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-video#45]
I know there are a million issues around rewind / fast forward etc. but I've heard from a few people that they would at least like to know how long it is / where they are.  I wonder if it wouldn't be too disruptive to just show a play bar along with the pause button?   I'm mixed about this but just reporting the query.

**Comment by scottgarner** [comment]
I think it's a valid point. I added a little progress bar at the bottom, let me know what you think.

**Comment by shiffman** [comment]
The progress bar looks great to me.
