### ISSUE TITLE
Codebase doesn't seem to be updated with hello.p5js.org site

### ISSUE THREAD

**Issue by himanshuc3** [processing/p5.js-video#59]
According to https://github.com/processing/processing/wiki/Project-List#-updated-hellop5jsorg-site - hello.p5js.org has this as its codebase. But the index.html file itself is a lot different.

**Comment by scottgarner** [comment]
Different in what way? Keep in mind that the is a Jekyll site, so some templates and such are include when the project is deployed.

**Comment by himanshuc3** [comment]
I haven't worked with Jekyll, so I don't know about that.
But for starters, the local copy of index.html doesn't work in my browser whereas the production code does. And when I inspected the hello.p5js.org site there were meta tags, link tags etc. which I don't see in the repo index file. Is this difference too because of Jekyll?

**Comment by scottgarner** [comment]
The YAML at the head of index.html is replaced with a layout from the _layouts directory.

You won't be able to run the site locally without Jekyll. Learn more about Jekyll here:

https://jekyllrb.com

**Comment by himanshuc3** [comment]
gotcha. Btw since this site is up to be revamped, do you intend to still run this through Jekyll or let it be independent from it?

**Comment by scottgarner** [comment]
Good question! The reason we went with Jekyll at the time is because it integrates so well with GitHub pages, which meant free hosting, free CDN and a platform people were used to.

That still might be a good plan, but it will ultimately be up to whomever leads the revamp.

**Comment by himanshuc3** [comment]
I get it. Thanks for being so **clear**! 
P.S Went `blank space` of any adjectives :sweat_smile:
