### ISSUE TITLE
URL

### ISSUE THREAD

**Issue by scottgarner** [processing/p5.js-video#6]
The easiest thing is to point a subdomain of p5js.org to scottgarner.github.io with a CNAME entry.

Thoughts on the best naming? intro.p5js.org? hello.p5js.org?

**Comment by evhan55** [comment]
hello.p5js.org sounds good to me!  But I don't have a huge preference

**Comment by lmccart** [comment]
yup, like it!

**Comment by scottgarner** [comment]
Great, I'll add the CNAME file to the repository shortly when I push some updates.

Looks like you're using Dreamhost's  DNS servers? Can one of you log in and add a CNAME pointing hello.p5js.org to scottgarner.github.io?

https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages
http://wiki.dreamhost.com/CNAME_record

**Comment by lmccart** [comment]
great, updating now..

**Comment by scottgarner** [comment]
Perfect, looks like it's working. If you decide on a different domain, just update the CNAME record and change the value in the CNAME file in the root of the repository.
