### ISSUE TITLE
Example Sketches

### ISSUE THREAD

**Issue by scottgarner** [processing/p5.js-video#7]
I thought I'd start an issue to keep track of example development while I make a pass at incorporating the sketches @shiffman has done so far and putting in placeholders for everything else.

One initial question for @lmccart: The new p5.dom addon seems to work really well, but what's the most correct way to remove elements it creates? It would be nice to remove them all in one go at the sketch level, but the ability to remove them individually would work, too—especially if the sketch exposed an array of them.

**Comment by scottgarner** [comment]
Here's a quick check-in on the animations as they stand now and places where I could use some input.

_00:06, 00:09, 00:13_

Lauren gestures, but we haven't talked about what might work for animation.

_00:32_

I've dropped in Dan's initial drawing example. I ported it to instance mode and use its sketch.js directly in the video. I think it might be easiest for us to build everything in instance mode for now and backport to global mode for user examples.

I took out the setTimeouts and switched to Popcorn. I fade everything out with jQuery because that's easiest. Is that cheating?

_00:46_

Dan says he's "here in your web browser". It might be cool to have a sketch that demonstrates that in some way.

_00:52_

I dropped in Dan's elements example with the same notes as the drawing example above.

_01:08_

Dan mentions code. It might be nice to have a quick animation that scrolls some code.

_01:12_

Circle sketch. As above, I switched everything to instance mode and use its sketch.js in the video. Rather than toggling a color on click, I select a new color every time.

I switched everything to HSB because it makes it easier to work with a consistent palette. I also personally think HSB is an easier concept to deal with than RGB, even with the added colormode call, but that's up for debate.

I noticed that the mouse event seems to be attached to the window rather than the canvas. We could catch that in the code, but I was surprised.

_01:21_

I switched to a pause button in the corner. (None of the pause examples work yet.) I'm a little unsure of the code editor at this point, particularly when we get to super involved examples like flocking. I also think it would be better to pop people to a real, web-based p5.js IDE when/if one exists.

_01:36_

Same as the circle sketch, but with a slider for hue. When I remove this sketch (and other sketches with HTML elements) I'm using jQuery's empty(). Maybe there's a more p5-appropriate way.

_01:50_

I reworked the flocking example for instance mode and made a lot of little tweaks. At this timecode I draw circles to the screen with hue and size determined by mouse proximity. I'll probably throw in some controls, too.

I noticed that a newly instantiated sketch sees the mouse at 0,0 until it is moved instead of the actual initial position.

_01:53_

This event just turns on flocking. If we reshoot, we should specifically mention that the boids are following the mouse. It also gets a little clumpy—maybe the mouse should repel instead of attract?

_02:10_

I redid the weather display and I'm not sure it was the best choice. I like the idea of having HTML and CSS already in place to act as a template for p5 to fill in the blanks, but this may not be the best approach for demonstration purposes and it does require dealing directly with the element itself, which can be a little clumsy.

I also noticed that the wind direction seems to be 90 degrees off when fed through sketch.radians() and used to create a p5.Vector. I'm not sure what the problem is.

_02:38_

I'm a little stuck with the video and finding the right way to use p5.js to show it. The first problem is easy enough to fix, which is that we need to be able to supply multiple source files for different browsers (.mp4 for Safari, .webm for Firefox, etc.) The second problem is trickier. To make this demo work, the video should be fully buffered and ready to display before the Popcorn event fires. This doesn't really work with the way sketches are now loaded.

The obvious solution would be to handle the video buffering and such outside of p5, but then you'd just show it and hit play with Popcorn and p5 wouldn't even be used.

_03:22_

I just animated in a draft version of a "call to action" panel.

**Comment by shiffman** [comment]
> I've dropped in Dan's initial drawing example. I ported it to instance
> mode and use its sketch.js directly in the video. I think it might be
> easiest for us to build everything in instance mode for now and backport to
> global mode for user examples.
> 
> Agreed.
> 
> I took out the setTimeouts and switched to Popcorn. I fade everything out
> with jQuery because that's easiest. Is that cheating?
> 
> I think it's ok.
> 
> Dan mentions code. It might be nice to have a quick animation that scrolls
> some code.
> 
> Yes, especially if we do away with the pause feature.
> 
> Circle sketch. As above, I switched everything to instance mode and use
> its sketch.js in the video. Rather than toggling a color on click, I select
> a new color every time.
> 
> I switched everything to HSB because it makes it easier to work with a
> consistent palette. I also personally think HSB is an easier concept to
> deal with than RGB, even with the added colormode call, but that's up for
> debate.
> 
> I noticed that the mouse event seems to be attached to the window rather
> than the canvas. We could catch that in the code, but I was surprised.
> 
> this is how p5 works.  mousePressed() is attached to the window.  If we
> want it to be attached to canvas only it's

```
var canvas = createCanvas(w,h);
canvas.mousePressed = function() {

};
```

> I switched to a pause button in the corner. (None of the pause examples
> work yet.) I'm a little unsure of the code editor at this point,
> particularly when we get to super involved examples like flocking. I also
> think it would be better to pop people to a real, web-based p5.js IDE
> when/if one exists.
> 
> Yeah, I'm not sure this will be that effective for the complex examples.
> 
> _01:36_
> 
> Same as the circle sketch, but with a slider for hue. When I remove this
> sketch (and other sketches with HTML elements) I'm using jQuery's empty().
> Maybe there's a more p5-appropriate way.
> 
> I don't think remove() has been implemented yet but it's planned.
> https://github.com/lmccart/p5.js/issues/227#issuecomment-46752560

_01:50_

> I reworked the flocking example for instance mode and made a lot of little
> tweaks. At this timecode I draw circles to the screen with hue and size
> determined by mouse proximity. I'll probably throw in some controls, too.
> 
> I noticed that a newly instantiated sketch sees the mouse at 0,0 until it
> is moved instead of the actual initial position.
> 
> I think it might be nice if the larger circle shrinks to a smaller one,
> then new circles are added, and the flock together.  I can work on this if
> you like.
> 
> _01:53_
> 
> This event just turns on flocking. If we reshoot, we should specifically
> mention that the boids are following the mouse. It also gets a little
> clumpy—maybe the mouse should repel instead of attract?

Yes, let's do the repel, that'll be nice.  I'll incorporate that.

> _02:10_
> 
> I redid the weather display and I'm not sure it was the best choice. I
> like the idea of having HTML and CSS already in place to act as a template
> for p5 to fill in the blanks, but this may not be the best approach for
> demonstration purposes and it does require dealing directly with the
> element itself, which can be a little clumsy.
> 
> I also noticed that the wind direction seems to be 90 degrees off when fed
> through sketch.radians() and used to create a p5.Vector. I'm not sure what
> the problem is.

I'll check on the angle thing.  I like the design for the weather info.

**Comment by lmccart** [comment]
> _00:46_
> 
> Dan says he's "here in your web browser". It might be cool to have a
> sketch that demonstrates that in some way.
> 
> open 100 tabs really fast? JK. maybe. we could go wilderness downtown style
> on it for a second. I really just want to see more "how do I delete dan
> shiffman from my computer?" issues on the forum. but there isn't anything
> particularly for handling opening tabs in p5.js right now. maybe something
> using resizeTo?
> 
> I noticed that the mouse event seems to be attached to the window rather
> than the canvas. We could catch that in the code, but I was surprised.
> 
> The thinking here is that your sketch is more than your canvas, or it will
> be once the dom stuff is set. (To that end, there is also mouseX/Y relative
> to canvas then winMouseX/Y relative to 0,0 of the window.) So if you wanted
> to bind to canvas only you'd use the element specific .mousePressed()
> method. See this example:
> https://github.com/lmccart/p5.js/blob/master/examples/instantiation-instance/case6/sketch.js
> 
> _01:21_
> 
> I switched to a pause button in the corner. (None of the pause examples
> work yet.) I'm a little unsure of the code editor at this point,
> particularly when we get to super involved examples like flocking. I also
> think it would be better to pop people to a real, web-based p5.js IDE
> when/if one exists.

this would be great, but unlikely in the immediate future

> _01:36_
> 
> Same as the circle sketch, but with a slider for hue. When I remove this
> sketch (and other sketches with HTML elements) I'm using jQuery's empty().
> Maybe there's a more p5-appropriate way.
> 
> Working on the dom remove methods. Both element specific ones and a general
> remove() that takes everything out, or maybe sketch.remove() will do this.
> Hoping to have something in the next couple days, p5.dom is my focus right
> now.
> 
> _01:50_
> 
> I reworked the flocking example for instance mode and made a lot of little
> tweaks. At this timecode I draw circles to the screen with hue and size
> determined by mouse proximity. I'll probably throw in some controls, too.
> 
> I noticed that a newly instantiated sketch sees the mouse at 0,0 until it
> is moved instead of the actual initial position.
> 
> _01:53_
> 
> This event just turns on flocking. If we reshoot, we should specifically
> mention that the boids are following the mouse. It also gets a little
> clumpy--maybe the mouse should repel instead of attract?
> 
> _02:10_
> 
> I redid the weather display and I'm not sure it was the best choice. I
> like the idea of having HTML and CSS already in place to act as a template
> for p5 to fill in the blanks, but this may not be the best approach for
> demonstration purposes and it does require dealing directly with the
> element itself, which can be a little clumsy.
> 
> Are there any methods that seem obviously lacking right now from the dom
> addon? I can add some more of those in.
> 
> _02:38_
> 
> I'm a little stuck with the video and finding the right way to use p5.js
> to show it. The first problem is easy enough to fix, which is that we need
> to be able to supply multiple source files for different browsers (.mp4 for
> Safari, .webm for Firefox, etc.) The second problem is trickier. To make
> this demo work, the video should be fully buffered and ready to display
> before the Popcorn event fires. This doesn't really work with the way
> sketches are now loaded.
> 
> I think Jason added some methods recently to p5.dom that allows you to
> specify several options for video formats for fallback. Let me know if this
> needs more still and we can add it.

Maybe there needs to be a loadVideo method in addition to createVideo that
could be placed in preload or called with a callback. Can you post a little
gist of the ideal behavior, or what you're trying to do and I'll try to add
it in?

I like the idea of not showing the live code. This allows us to fudge
things a little more now with popcorn, and then focus on writing simplified
examples that do what we're showing in the demo a little later when the
p5.dom stuff is more nailed down.

**Comment by scottgarner** [comment]
Here are some notes on the p5 specific stuff. I'll take the example-specific stuff to the new script issue.
- mousePressed()

That makes total sense.
- remove()

I'm a little divided on the perfect implementation. At first thought, it makes sense to me that sketch.remove() would also remove any elements created by that sketch, but I'm sure there are cases where that wouldn't be desirable.
- dom

One thing I'm missing at the moment is a way to set the value of text-based elements like a div. jQuery offers .text() and .html() for element.innerText and element.innerHTML respectively, but I could see just making .value() set innerHTML for these elements.

size() doesn't seem to work immediately after showing a hidden element. jQuery has some magic for handling this, but I'm not sure what it is.

Class management functions would be nice (addClass, removeClass, toggleClass) as well as attr() and css() for setting attributes and styles, but maybe that's getting too heavy.

Finally, I'm not sure which way makes more sense, but either something like addChild() on a div to place elements inside it or parent() on all elements to put them inside a div would be handy, but might open up a lot of weird possibilities.
- createVideo()

I guess the underlying problem is that just because you create an element doesn't mean you have access to the media yet. This is also an issue with createImg() since you could create an image and immediately ask for its size, which would probably give the wrong answer because it hasn't loaded.

With images on the web, you'd normally attach a listener to `onload` and do your stuff after that, which doesn't really have a prefect analog in Processing. I guess it could be designed to function like libraries that offer available(). You can also do the trick where you preload an image by referencing it when the document loads so it's already there when a script needs it later.

You can't really do that with videos and there are a number of other events to worry about. I don't enable the play button for the main video here, for example, until `canplaythrough` fires because I don't want any weird streaming or stuttering problems. In other instances you might want to start when `canplay` fires instead.

This is slightly moot since we're skipping the video example, but it's something to consider in the long run. In this case, I couldn't instantiate a sketch at a given timecode and immediately play a video through to the end reliably.

**Comment by lmccart** [comment]
thanks! this is helpful...

.html() is there, so is .parent(), let me know if either aren't working. 
http://p5js.org/site/reference/

maybe .child() makes sense to add too...

will look into the .size() issues

yes, def agree about .css() .attr() and .addClass or somethings like that.

ill check out the video stuff, too.

I think I'd like to make these all getters (with no args) as well as setters at some point too.

**Comment by scottgarner** [comment]
Oh, sorry! I see now that html() and parent() are in p5 proper. I was looking for them in the dom addon.

I guess it's slightly confusing that you can call value() on any p5.Element without getting an error, but in some cases (div, etc.) it does nothing.

**Comment by lmccart** [comment]
my plan for remove is as follows:
- core `remove()` does all the things it does currently: stop p5, remove event handlers, remove canvas, delete p5
- for any p5.Element (canvas or those created with dom module), you can call `elt.remove()` and it removes any handlers associated with that item and removes it from the dom
- method `removeElements()` in the dom lib will call `elt.remove()` on all elements created by that instance of p5, except the original canvas.

so, to remove a sketch entirely, if it uses the dom lib also, you would call

``` javascript
removeElements();
remove();
```

(removeElements needs to go first because remove nukes the whole p5 thing)

sound ok?

**Comment by scottgarner** [comment]
Sounds great!

**Comment by lmccart** [comment]
updated ref here:
http://p5js.org/site/reference/#/libraries/dom

still working on filling in more copy and examples, but I think this gives a better overview of what's currently implemented

**Comment by scottgarner** [comment]
In looking over some other jQuery stuff I'm doing that could be replaced with p5, an obvious instance is fadeIn() and fadeOut(). I'm not sure if it makes sense to include that in the dom addon or in another effects/animation addon. I suppose it could also just be done with a generic tween addon, but then you couldn't take advantage of hardware acceleration in CSS animations.

**Comment by shiffman** [comment]
I think the fadein/out functionality is a bit beyond the scope of the p5.js dom library. . I could imagine a CSS animation add-on for p5 someday but I think it's really ok to use JQuery for this functionality.  Better to spend our energy on other things?

**Comment by lmccart** [comment]
yeah, I think I agree. maybe at some point some more generic css tween function, but I'd like to solidify the core of these methods first.

on another note, I've got addClass and removeClass ready to go, but trying to think what makes sense in terms of naming. it was nice to have the one word `id()` and `class()`. should `class()` become `addClass()`, or should we keep `class()` and just add `removeClass()`?

**Comment by shiffman** [comment]
can a DOM element belong to multiple classes?  Is that the issue?

**Comment by lmccart** [comment]
yes, exactly. generally an ID is used once on a page, and an element has one at most. with classes, they are used across multiple elements, and a single element may have more than one class. right now the class() method just sets the class field, so if you wanted to add multiple you'd write: 

``` javascript
elt.class('pigs candles');
```

to remove a class you'd overwrite it

``` javascript
elt.class('pigs');
```

but it'd probably be nice to have a removeClass method. alternatively, calling class() with no arguments could act as a getter, and leave the removal and string manipulation up to the user. something like..

``` javascript
var c = elt.class(); // gets string of cur classes
c = c.replace('candles', ''); // remove candles from string
elt.class(c); // set class to remaining filtered string
```

**Comment by shiffman** [comment]
Got it.  Tough one, I love the simplicity of `class()` but feels best to relieve the user of any string parsing.  So I think it makes sense to have `addClass(s)` and `removeClass(s)`.   I suppose we could also keep `class` as a means of overwriting the class.  We could also consider having it accept/return an array for multiple classes.

**Comment by scottgarner** [comment]
This discussion just reminded me that I can make a CSS animation for fading out and apply it by adding a class.

I'm biased by the jQuery method, but addClass() and removeClass() have always seemed intuitive to me because, as mentioned above, you often find yourself dealing with multiple classes and something about class() seems singular. I do find myself using its toggleClass() a fair amount, too. There is also a hasClass(), but for whatever reason I don't rely on that much—probably because toggleClass() checks that itself.

For setting several classes or removing all classes, jQuery doesn't offer a class(), but instead recommends using attr('class', "this that"). That has always seemed a little strange to me, though, and I could see class() as a direct getter and setter working or even optionally taking an array.

**Comment by lmccart** [comment]
I like that. also, I'm thinking that `id()` and `class()` will be in core, to add minimal canvas positioning help. then `addClass()` and `removeClass()` will be in the dom library.

I like the idea of accepting and returning an array or value in class().

**Comment by lmccart** [comment]
I've switched the signature around a bit so createVideo and createAudio take single elements or arrays, so you can input an array of files for supporting diff browsers.

I also added an optional second callback arg that fires on 'canplaythrough'. I can also get it working with preload(). However, I'm not sure this is right, as you mention, there are different events. Would it make more sense to have some more generic .onEvent(str, fxn) method?

I guess all irrelevant since we're not doing the video part, but would be curious to hear your thoughts since you were playing around with this.

http://p5js.org/reference/#/p5.dom/createVideo

**Comment by scottgarner** [comment]
So maybe by default the callback triggers on "canplaythrough" (or whatever seems most appropriate) and you offer another means of calling the functions that takes an object of options. It's pretty common in other libraries for advanced customization.

```
createVideo({
  source: [...],
  callback: function() {...},
  callbackEvent: "canplaythrough",
  ...
});
```

I still wonder, too, if it might be good to have something like .available() for beginners who might find callbacks daunting.
